AWSTemplateFormatVersion: 2010-09-09

Parameters:
  RootBucketName:
    Description: Unique base name for your app that will be used in prod and staging bucket names.
    Type: String

Resources:
  ProdBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RootBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain
  StagingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Join
        - ''
        - - 'staging.'
          - !Ref RootBucketName
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
      DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProdBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ProdBucket
                - /*

Outputs:
  WebsiteURL:
    Value: !GetAtt
      - ProdBucket
      - WebsiteURL
    Description: URL for website hosted on S3
#  S3BucketSecureURL:
#    Value: !Join
#      - ''
#      - - 'https://'
#        - !GetAtt
#          - ProdBucket
#          - DomainName
#    Description: Name of S3 bucket to hold website content