# Javascript Node CircleCI 2.0 configuration file
# change for build 3
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
orbs:
    cypress: cypress-io/cypress@1
    aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn ci:cypress

      # build and deploy
      - run: yarn build:prod
      - aws-s3/sync:
          from: bucket
          to: 's3://react-spa-starter-production/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
      - aws-s3/copy:
          from: bucket/build_aßsset.txt
          to: 's3://my-s3-bucket-name'
          arguments: '--dryrun'